# Generated by Django 5.0.4 on 2025-08-26 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="category_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="order_main_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_amount", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="product_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("photo", models.ImageField(upload_to="")),
                ("details", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="contractor_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=100)),
                ("phone_no", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="")),
                ("proof", models.ImageField(upload_to="")),
                ("status", models.CharField(max_length=100)),
                (
                    "LOGIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="assign_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=100)),
                (
                    "ORDER_MAIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.order_main_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_amount", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
                (
                    "ORDER_MAIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.order_main_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_sub_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "ORDER_MAIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.order_main_table",
                    ),
                ),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="offer_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entry", models.DateField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("offer_name", models.CharField(max_length=100)),
                ("offer_price", models.IntegerField()),
                ("details", models.CharField(max_length=300)),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shop_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone_no", models.IntegerField()),
                ("place", models.CharField(max_length=100)),
                ("post", models.CharField(max_length=100)),
                ("pincode", models.IntegerField()),
                ("district", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="")),
                ("proof", models.ImageField(upload_to="")),
                ("status", models.CharField(max_length=100)),
                (
                    "LOGIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product_table",
            name="SHOP",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.shop_table"
            ),
        ),
        migrations.AddField(
            model_name="order_main_table",
            name="SHOP",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.shop_table"
            ),
        ),
        migrations.CreateModel(
            name="user_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone_no", models.IntegerField()),
                ("place", models.CharField(max_length=100)),
                ("post", models.CharField(max_length=100)),
                ("pincode", models.IntegerField()),
                ("district", models.CharField(max_length=100)),
                (
                    "LOGIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="review_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("review", models.CharField(max_length=500)),
                ("rating", models.FloatField()),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product_table",
                    ),
                ),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="return_product_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(max_length=300)),
                ("status", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="")),
                (
                    "ORDER_MAIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.order_main_table",
                    ),
                ),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order_main_table",
            name="USER",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.user_table"
            ),
        ),
        migrations.CreateModel(
            name="feedback_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("feedback", models.CharField(max_length=300)),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="complaint_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("complaint", models.CharField(max_length=500)),
                ("reply", models.CharField(max_length=500)),
                ("status", models.CharField(max_length=100)),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.IntegerField()),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product_table",
                    ),
                ),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="work_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="")),
                ("description", models.CharField(max_length=300)),
                ("rate", models.IntegerField()),
                (
                    "CONTRACTOR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.contractor_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="request_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=100)),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
                (
                    "WORK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.work_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="worker_review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("review", models.CharField(max_length=300)),
                ("rating", models.FloatField()),
                (
                    "REQUEST",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.request_table",
                    ),
                ),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.user_table",
                    ),
                ),
            ],
        ),
    ]
