# Generated by Django 5.0.4 on 2025-08-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor_table",
            name="phone_no",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="shop_table",
            name="phone_no",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="user_table",
            name="phone_no",
            field=models.BigIntegerField(),
        ),
    ]
