# Generated by Django 5.0.4 on 2025-09-15 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_contractor_table_phone_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart_table",
            name="CONTRACTOR",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.contractor_table",
            ),
        ),
        migrations.AlterField(
            model_name="cart_table",
            name="USER",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user_table",
            ),
        ),
    ]
