# Generated by Django 5.0.4 on 2025-09-15 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_cart_table_contractor_alter_cart_table_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart_table",
            name="CONTRACTOR",
        ),
        migrations.RemoveField(
            model_name="cart_table",
            name="USER",
        ),
        migrations.AddField(
            model_name="cart_table",
            name="lOGIN",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
