# Generated by Django 5.0.4 on 2025-09-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_cart_table_contractor_remove_cart_table_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order_main_table",
            name="SHOP",
        ),
    ]
