# Generated by Django 5.0.4 on 2025-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_order_main_table_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback_table",
            name="rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
